### ISSUE TITLE
TypeError: Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by diamont1001** [madrobby/zepto#1222]
What's happening?

There is an error testing here: https://tonicdev.com/npm/zepto

**Comment by temoto** [comment]
What's happening is scope wrapper `(function(window){ ... }())` received empty object for some reason.
This also reproduces under browserify builds.

Mad workaround (then you'll need to add more):
```
  Object.prototype.document = window.document;
  Object.prototype.location = window.location;
  var $ = require('zepto').$;
  delete(Object.prototype.document);
  delete(Object.prototype.location);
```

**Comment by ringcrl** [comment]
@temoto 
work for me

**Comment by positlabs** [comment]
I've seen this happen in commonjs / browserify environments before. The issue is that the scope wrapper doesn't live in `window`... rather it is wrapped in another scope wrapper, so `this` becomes a reference to the outer wrapper, and not `window` as is assumed by the zepto scope wrapper. 
```
(function(global, factory) {
  if (typeof define === 'function' && define.amd)
    define(function() { return factory(global) })
  else
    factory(global)

// this should window
// }(this, function(window) {
}(window, function(window) {
```

**Comment by positlabs** [comment]
Same issue as #1210

**Comment by Evans-Cai** [comment]
thanks

2016-12-02 4:33 GMT+08:00 Josh Beckwith <notifications@github.com>:

**Comment by temoto** [comment]
Why wouldn't one just use name `window` inside any/all wrappers?

**Comment by positlabs** [comment]
I've created a PR here: https://github.com/madrobby/zepto/compare/master...positlabs:patch-1

**Comment by madrobby** [comment]
This should work now on the `master` branch. Please try again and feel free to reopen this issue if it doesn't work correctly.

**Comment by KroniK907** [comment]
I don't think this works properly, at least not when using webpack. I'm still getting the same TypeError.

**Comment by Lenic** [comment]
same to me...

**Comment by positlabs** [comment]
Can you provide a failing test case?

**Comment by braxnu** [comment]
Hi, please do `npm run build` on this https://github.com/braxnu/zepto-factory-scoping-fail-proof

**Comment by positlabs** [comment]
@braxnu please use master branch, not v1.2.0. Zepto hasn't had a version bump since this PR was merged. 

@madrobby do you think it's possible to bump to v1.2.1, then publish to npm?

**Comment by ataylorme** [comment]
> @madrobby do you think it's possible to bump to v1.2.1, then publish to npm?

+1 to this. I'm pulling in Zepto with Browserify and am seeing this error. A new version published to NPM would be appreciated.

**Comment by p** [comment]
@madrobby Can we get a fixed version on npm please?

For others experiencing this issue, #1244 contains a workaround for webpack.

**Comment by chanelnumberfive** [comment]
i agree with positlabs's idea ,use window instead of this and it work when i using webpack!
`(function(global, factory) {
  if (typeof define === 'function' && define.amd)
    define(function() { return factory(global) })
  else
    factory(global)

// this should window
// }(this, function(window) {
}(window, function(window) {`

**Comment by chanelnumberfive** [comment]
i agree with positlabs's idea ,use window instead of this and it work when i using webpack!
<pre><code>(function(global, factory) {
if (typeof define === 'function' && define.amd)
define(function() { return factory(global) })
else
factory(global)

// this should window
// }(this, function(window) {
}(window, function(window) {</code></pre>

**Comment by LMCom** [comment]
I'm using webpack with Zepto 1.2.0. The browser console:
Uncaught TypeError: document is undefined
    Zepto zepto.js:23

Line 23 is the last line in the following snippet. `window` cannot be undefined, otherwise there would have been a null reference in line 4. It is an empty object and does not have the property `document`. I verified this.
I'm importing Zepto via `import 'zepto';`. Is this correct?

```javascript
(this, function(window) {
  var Zepto = (function() {
  var undefined, key, $, classList, emptyArray = [], concat = emptyArray.concat, filter = emptyArray.filter, slice = emptyArray.slice,
    document = window.document,
    elementDisplay = {}, classCache = {},
    cssNumber = { 'column-count': 1, 'columns': 1, 'font-weight': 1, 'line-height': 1,'opacity': 1, 'z-index': 1, 'zoom': 1 },
    fragmentRE = /^\s*<(\w+|!)[^>]*>/,
    singleTagRE = /^<(\w+)\s*\/?>(?:<\/\1>|)$/,
    tagExpanderRE = /<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,
    rootNodeRE = /^(?:body|html)$/i,
    capitalRE = /([A-Z])/g,

    // special attributes that should be get/set via method calls
    methodAttributes = ['val', 'css', 'html', 'text', 'data', 'width', 'height', 'offset'],

    adjacencyOperators = [ 'after', 'prepend', 'before', 'append' ],
    table = document.createElement('table'),
```
